language: scala
# Use container-based infrastructure
sudo: false
jdk:
- oraclejdk8
scala:
- 2.12.6
script:
  - sbt -S ";clean;coverage;test;coverageReport"
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
